.travis.yml

* Set sudo: false. This allows Travis to use the new container-based
infrastrukture, which should speed up the builds.
* Enable bundler caching.
Closes #9

[TASK] Configure Travis for better performance

---

.travis.yml
page_title_helper.gemspec

Ruby 1.9.3 was end-of-lifed on 2015-02-23.
Closes #24

[TASK] Drop support for Ruby 1.9.x

---

lib/page_title_helper.rb

It suffices to require the file from the gemspec file.
Fixes #43

[CLEANUP] Stop requiring version from the  main class

---

.travis.yml
init.rb
test/test_helper.rb

The init.rb file dates back to Rails 2 plugins, if I recall correctly.
Fixes #57

Delete obselete init.rb file

---

.travis.yml

As we are now using Ruby 2.3.4 in Travis, the workaround is no longer needed
for the CI. This should speed up the builds a bit.

[TASK] Remove workaround for Ruby 2.3.3

---

page_title_helper.gemspec
test/multiple_formats_test.rb
test/page_title_helper_test.rb

Was only potentially impacting development and not any running instances or usages of the gem. In addition had to update a few tests as rubocop 0.49  complained about missing parentheses.
FYI, upgrade to version 0.5x of rubocop is only possible when we drop support for Ruby 2.0.
@oliverklee please review and merge, thanks.

Update rubocop to .49 to fix dev vuln

---

.rubocop.yml
.travis.yml
CHANGELOG.md
Gemfile
Rakefile
gemfiles/Gemfile.rails-4-2
gemfiles/Gemfile.rails-5-0
gemfiles/Gemfile.rails-5-1
gemfiles/Gemfile.rails-5-2
lib/page_title_helper.rb
lib/page_title_helper/version.rb
page_title_helper.gemspec
test/multiple_formats_test.rb
test/page_title_helper_test.rb
test/test_helper.rb

Ruby 2.3 has reached its end of life:
https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/

[TASK] Drop support for Ruby < 2.4

---

.rubocop.yml
.travis.yml
CHANGELOG.md
README.md
gemfiles/Gemfile.rails-4-2
gemfiles/Gemfile.rails-5-0
gemfiles/Gemfile.rails-5-1
page_title_helper.gemspec

All Rails versions below 5.2 have reached their end of life.

[TASK] Drop support for Rails < 5.2

---

.travis.yml
CHANGELOG.md

- drop the obsolete `sudo` option
- make the `os` option explicit

[CLEANUP] Fix warnings in the .travis.yml

---

.travis.yml

- explicitly set the Linux distribution
- replace the alias `matrix` with `jobs`

[CLEANUP] Fix notices in the .travis.yml

---

.travis.yml
CHANGELOG.md
page_title_helper.gemspec

Ruby 2.4 has reached its end of life:
https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/
Also drop the rubygems version requirement as this gem does not
depend on this.

[TASK] Drop support for Ruby 2.4

---

CHANGELOG.md

This way, we do not need to manually add issue/PR links to the
changelog anymore (which was a pain to maintain).

[CLEANUP] Use GitHub's issue/PR autolinking in the changelog

---

.github/workflows/ci.yml
CHANGELOG.md

`ruby/setup-ruby` is the better action to use for installing Ruby
in GitHub Actions (particularly for more recent Ruby versions);
`actions/setup-ruby` is not.

[BUGFIX] Use a maintained action for installing Ruby for the CI builds

---

.github/workflows/publish.yml
CHANGELOG.md

This new GitHub Actions workflow will automatically publish the
gem to RubyGems when a new release is tagged with the `v` prefix,
e.g., `v5.0.0`.
For authentication, there needs to be a secret with the key
`RUBYGEMS_API_KEY` configured in the GitHub repository configuration.
The stored rubygems.org API key needs to have gem publication permissions,
and two-factor authentication for the corresponding rubygems.org account
should only be enabled for the UI, but must not be enabled for the API
(as there is no way to enter the second factor when the GitHub action
is run).

[FEATURE] Add automatic gem release

---

CHANGELOG.md
lib/page_title_helper/version.rb

[TASK] Prepare the 5.0.0 release

---

.github/workflows/ci.yml
.rubocop.yml
CHANGELOG.md
page_title_helper.gemspec

[TASK] Drop support for Ruby 2.5

---

.github/workflows/ci.yml

This will allow us to have combinations in the future that exclude
some elements of the cross product between all possible Ruby and Rails
versions (e.g., use Ruby 3.1 builds only with newer Rails versions).

[TASK] Explicitly set all values in the CI build matrix

---

.rubocop.yml

Now that all rules are enabled by default, we do not need
to enable the rules individually anymore.

[CLEANUP] Drop redundant RuboCop rule switches

---

.github/workflows/ci.yml
.rubocop.yml
CHANGELOG.md
page_title_helper.gemspec

The EOL of Ruby 2.6 is 2022-03-31:
https://www.ruby-lang.org/en/downloads/branches/
Fixes #136

[TASK] Drop support for Ruby 2.6

---

.github/workflows/ci.yml
.github/workflows/publish.yml

This change includes the latest security releases for Ruby.
Also switch the release workflow from Ruby 3.0 to Ruby 3.1.

[TASK] Update the Ruby versions on CI

---

.github/workflows/ci.yml
.github/workflows/publish.yml

This keeps stuck jobs from unnecessarily hogging CI resources.

[TASK] Limit the runtime of the CI jobs

---

.github/workflows/ci.yml
.rubocop.yml
CHANGELOG.md
page_title_helper.gemspec

Ruby 2.7 is EOL now:
https://www.ruby-lang.org/en/news/2023/03/30/ruby-2-7-8-released/

[TASK] Drop support for Ruby 2.7

---

.github/workflows/ci.yml
.rubocop.yml
CHANGELOG.md
gemfiles/Gemfile.rails-5.2
page_title_helper.gemspec

Rails 5.2 is EOL now:
https://endoflife.date/rails
Fixes #137

[TASK] Drop support for Rails 5.2

---

.github/workflows/ci.yml
CHANGELOG.md

Also switch the code quality CI job to Ruby 3.3.
The gem publication CI job stays at Ruby 3.2 for now (to play it safe).
Fixes #176

[FEATURE] Add official support for Ruby 3.3

---

.github/workflows/ci.yml
.rubocop.yml
CHANGELOG.md
lib/page_title_helper.rb
page_title_helper.gemspec

Ruby 3.0 has been EOL'ed:
https://www.ruby-lang.org/en/news/2024/04/23/ruby-3-0-7-released/
Also make use of some Ruby 3.1 features.
Fixes #181

[TASK] Drop support for Ruby 3.0

---

.github/workflows/ci.yml
.rubocop.yml
CHANGELOG.md
gemfiles/Gemfile.rails-7.1
page_title_helper.gemspec

Rails 7.1 will be EOL on October 1st, 2025.
https://endoflife.date/rails

[TASK] Drop support for Rails 7.1
