.travis.yml
=> [TASK] Allow the Rails 3.2 build to fail only with Ruby 2.2

page_title_helper.gemspec
=> [CLEANUP] Use single quotes for strings in the gemspec file

.travis.yml, Gemfile, Rakefile, gemfiles/rails_4.2.gemfile, lib/page_title_helper.rb, test/multiple_formats_test.rb, test/page_title_helper_test.rb, test/test_helper.rb
This PR currently only exists to see the results of the Travis build.
=> [BUGFIX] Get the tests to run in Rails 4.2 and 5.0

page_title_helper.gemspec
=> 🎨 do not shell-out to `git` in Gemfile

README.md
- list Rails 4.2 and 5 instead of 3
- add a missing comma
[ci skip]
=> [CLEANUP] Polish the README

CODE_OF_CONDUCT.md
=> [TASK] Add a CODE_OF_CONDUCT.md

README.md
=> [TASK] Document that the project uses semantic versioning

README.md, page_title_helper.gemspec
- link it from the README.md
- add it to the list of files in the gemspec
=> [TASK] Link the code of conduct file

.rubocop.yml, lib/page_title_helper.rb
=> Fix @_page_title uninitialized warning

CHANGELOG.md, page_title_helper.gemspec
This file lists all changes that affect the way the Gem works or how it
can be used, but not non-functional cleanup.
Fixes #50
=> [TASK] Add a CHANGELOG.md

.travis.yml, CHANGELOG.md
=> [TASK] Add Ruby 2.4.0 to the build matrix

.rubocop_todo.yml, test/test_helper.rb
- remove trivial accessors
- remove unnecessary self
=> [CLEANUP] Fix more Rubocop warnings

CHANGELOG.md, CODE_OF_CONDUCT.md, README.md, gemfiles/Gemfile.rails-4-2, gemfiles/Gemfile.rails-5-0, gemfiles/Gemfile.rails-5-1, lib/page_title_helper.rb, page_title_helper.gemspec
=> [TASK] Use HTTPS for all URLs

.travis.yml, CHANGELOG.md, gemfiles/Gemfile.rails-6.0, page_title_helper.gemspec
=> [FEATURE] Add support for Rails 6.0

CHANGELOG.md, lib/page_title_helper/version.rb
Also split up the changelog between the 3.0.0 and 4.0.0 changes (which
accidentally got lumped together).
=> [TASK] Prepare the 4.0.0 release

CHANGELOG.md, README.md
- avoid double blank lines
- shorten overlong lines
- use MarkDown tables
- use syntax highlighting
=> [CLEANUP] Clean up the Markdown files

page_title_helper.gemspec
Tests pass locally, didn't see anything in the release notes that would make me think changes are needed.
=> Rails 6.1 Support

.travis.yml, CHANGELOG.md, gemfiles/Gemfile.rails-5-2, gemfiles/Gemfile.rails-6.1
Also update the patch level versions for Rails 5.2 and 6.0.
=> [FEATURE] Add Rails 6.1 to the CI builds

README.md
=> [BUGFIX] Fix the link to the code of conduct in the README

.github/workflows/ci.yml, .github/workflows/publish.yml
Now the used Ruby versions have the latest security updates.
=> [BUGFIX] Update the Ruby versions used for CI and publication

.gitignore
Also add the missing slash to the paths, and also sort the lines
in the `.gitignore`.
=> [TASK] Git-ignore directories related to local development

.github/workflows/ci.yml, .github/workflows/publish.yml
=> [TASK] Upgrade the GitHub runners to Ubuntu 22.04

.github/workflows/ci.yml, CHANGELOG.md, gemfiles/Gemfile.rails-7.1, page_title_helper.gemspec
https://rubyonrails.org/2023/10/5/Rails-7-1-0-has-been-released
=> [FEATURE] Add support for Rails 7.1

.github/workflows/ci.yml, .rubocop.yml, CHANGELOG.md, gemfiles/Gemfile.rails-6.0, page_title_helper.gemspec
=> [TASK] Drop support for Rails 6.0

.github/workflows/ci.yml, .github/workflows/publish.yml
=> [TASK] Security-update the Ruby versions on CI

.github/workflows/publish.yml
=> [TASK] Switch the gem publication job to Ruby 3.3

.github/workflows/ci.yml
=> [TASK] Use bundler caching on CI

.github/workflows/ci.yml
https://github.com/ruby/ruby/releases/tag/v3_2_5
=> [TASK] Update CI to Ruby 3.2.5

.github/workflows/ci.yml, gemfiles/Gemfile.rails-7.2, page_title_helper.gemspec
=> Add support for Rails 7.2

.github/workflows/ci.yml, .rubocop.yml, CHANGELOG.md, gemfiles/Gemfile.rails-6.1, page_title_helper.gemspec
=> [TASK] Drop support for Rails 6.1

CHANGELOG.md
=> [DOCS] Autoformat the changelog

.github/workflows/ci.yml, .github/workflows/publish.yml
https://github.com/ruby/ruby/releases/tag/v3_3_7
https://github.com/ruby/ruby/releases/tag/v3_4_1
=> [TASK] Bump the Ruby versions for CI

.github/workflows/ci.yml, .rubocop.yml, CHANGELOG.md, page_title_helper.gemspec
https://endoflife.date/rails
Fixes #210
=> [TASK] Drop support for Rails 7.0
